import { StyleSheet } from 'react-native';

export default StyleSheet.create({


  Scroll: {backgroundColor: '#1A72B6', width:'100%' ,},
  payHeader: { width: '100%', color : '#1A72B6', paddingVertical: '0', paddingHorizontal: '15%' , backgroundColor: '#000', flexDirection: 'row', alignItems: 'center' },
  payHeaderBtn: { width: '40%', height: 40, alignItems: 'center', justifyContent: 'center' },
  payHeaderTitle: { flex: 1, color: '#fff', fontSize: 17, fontWeight: 'bold', textAlign: 'center' },
  textpay: { color: '#1A72B6', fontSize:24  },

  container: { width: '100%', height: '100%', flex: 1, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' },
  scrollContent: { alignItems: 'center', paddingVertical: 40 },
  homeContainer: { width: '100%', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20 },
  homeTitle: { color: '#0B1C30', fontSize: 26, fontWeight: 'bold', textAlign: 'center', marginTop: 20 },
  homeSubtitle: { color: '#434655', fontSize: 15, textAlign: 'center', marginTop: 10, marginBottom: 20 },
  Texter: { alignItems: 'center', padding: '10%' },
  te: { color: '#0B1C30', textAlign: 'center', fontSize: 29, fontWeight: 'bold' },
  t: { color: '#434655', textAlign: 'center', fontSize: 14 },
  input: { width: '80%', borderWidth: 1, borderColor: '#ccc', borderRadius: 8, paddingVertical: 12, paddingHorizontal: 16, marginTop: 16, fontSize: 16 },
  pa: { paddingHorizontal: 0, width: '80%', fontSize: 16 },
  bu: { width: '80%' },
  passwordContainer: { width: '100%', flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#ccc', borderRadius: 8, marginTop: 16, paddingHorizontal: 11 },
  passwordInput: { flex: 1, paddingVertical: 12, fontSize: 16 },
  button: { width: '100%', paddingVertical: 14, borderRadius: 8, alignItems: 'center', textAlign: 'center', marginTop: 14 },
  buttonText: { width: '80%', color: '#fff', fontSize: 16, fontWeight: '600', textAlign: 'center' },
  textSection: { marginTop: 20, flexDirection: 'row', alignItems: 'center' },
  textSectionTitle: { color: '#666', fontSize: 14, marginRight: 4 },
  link: { color: '#0B1C30', fontSize: 14, fontWeight: '600' },
  forgot: { color: '#3F6BCD', fontSize: 14, fontWeight: '600', marginTop: 16, alignSelf: 'center', marginRight: '0' },
  error: { color: '#E3282C', fontSize: 14, marginTop: 12, textAlign: 'center' },
  dashRoot: { flex: 1, width: '100%', backgroundColor: '#F8FAF6' },
  dashHeader: { width: '100%', paddingVertical: 14, paddingHorizontal: 16, backgroundColor: '#3296E4', flexDirection: 'row', alignItems: 'center' },
  dashAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  dashAvatarImg: { width: 34, height: 34, resizeMode: 'contain' },
  dashHeaderText: { flex: 1, marginLeft: 12 },
  dashGreeting: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  dashSub: { color: '#D9E6F5', fontSize: 12, marginTop: 2 },
  dashScroll: { flex: 1 },
  dashScrollContent: { padding: 16, paddingBottom: 90 },
  screenContainer: { flex: 1, backgroundColor: '#fff' },
  screenScroll: { flex: 1, width: '100%'  },
  screenScrollContent: {padding: 20,  paddingBottom: 90 },
  heroCard: { backgroundColor: '#3296E4', borderRadius: 14, padding: 18, marginBottom: 20 },
  heroLabel: { color: '#D9E6F5', fontSize: 13 },
  heroBalance: { color: '#fff', fontSize: 30, fontWeight: 'bold', marginTop: 6 },
  heroRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  heroPhone: { color: '#fff', fontSize: 14, marginLeft: 6 },
  heroBtn: { backgroundColor: '#fff', borderRadius: 8, paddingVertical: 8, paddingHorizontal: 14, marginLeft: 'auto', alignItems: 'center' },
  heroBtnText: { color: '#0B1C30', fontSize: 13, fontWeight: '600' },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#0B1C30', marginTop: 4, marginBottom: 12 },
  serviceRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 14 },
  serviceBtn: { flex: 1, alignItems: 'center' },
  serviceCircle: { width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center' },
  serviceLabel: { fontSize: 12, color: '#434655', marginTop: 6 },
  promoCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 12, padding: 14, marginBottom: 20 },
  promoImg: { width: 48, height: 48, borderRadius: 24, resizeMode: 'contain' },
  promoTextWrap: { flex: 1, marginLeft: 12 },
  promoTitle: { fontSize: 15, fontWeight: 'bold', color: '#0B1C30' },
  promoSub: { fontSize: 12, color: '#434655', marginTop: 2 },
  txRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 12, padding: 12, marginBottom: 10 },
  txIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#F2F6FC', alignItems: 'center', justifyContent: 'center' },
  txTextWrap: { flex: 1, marginLeft: 10 },
  txTitle: { fontSize: 14, fontWeight: '600', color: '#0B1C30' },
  txDetail: { fontSize: 12, color: '#9AA3AE', marginTop: 2 },
  txAmount: { fontSize: 13, fontWeight: '600' },
  txPos: { color: '#2E9E4F' },
  txNeg: { color: '#E3282C' },
  bottomNav: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 64, paddingBottom: 8, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', borderTopWidth: 1, borderTopColor: '#E1E3E0' },
  navItem: { flex: 1, alignItems: 'center' },
  navLabel: { fontSize: 10, color: '#9AA3AE', marginTop: 2 },
  navLabelActive: { fontSize: 10, color: '#1A72B6', marginTop: 2 },
  settingsHeader: { width: '100%', paddingVertical: 14, paddingHorizontal: 16, backgroundColor: '#1A72B6', flexDirection: 'row', alignItems: 'center' },
  settingsHeaderTitle: { flex: 1, color: '#fff', fontSize: 17, fontWeight: 'bold', textAlign: 'center', borderRadius: '4'},
  dasheader: { width: '100%', marginBottom:'5%', paddingVertical: 14,backgroundColor: '#fff', paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center' , shadowColor: '#000000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 12},
  settingsProfileCard: {
    width: '95% ', backgroundColor: '#fff', borderRadius: 20, padding: 20, marginBottom: 20, alignItems: 'center', shadowColor: '#000000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 12 },
  settingsAvatar: { width: 96, height: 96, borderRadius: 48, backgroundColor: '#E1E3E0', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  settingsAvatarImg: { width: 92, height: 92, borderRadius: 46, resizeMode: 'contain' },
  settingsEditBadge: { position: 'absolute', right: 0, bottom: 0, width: 28, height: 28, borderRadius: 14, backgroundColor: '#1A72B6', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#fff' },
  settingsName: { fontSize: 18, fontWeight: 'bold', color: '#0B1C30', marginTop: 12 },
  settingsPhone: { fontSize: 14, color: '#434655', marginTop: 4 },
  settingsRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 12, padding: 14, marginBottom: 10 },
  settingsRowIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#F2F6FC', alignItems: 'center', justifyContent: 'center' },
  settingsRowText: { flex: 1, marginLeft: 12 },
  settingsRowTitle: { fontSize: 15, fontWeight: '600', color: '#0B1C30' },
  settingsRowSub: { fontSize: 12, color: '#9AA3AE', marginTop: 2 },
  settingsChevron: { fontSize: 18, color: '#9AA3AE' },

  // Payment methods screen
  //payRoot: {  backgroundColor: '#1A72B6', width:'100%' },
  creenScrollContent: { width: '100%',height :'10%', backgroundColor:'#f00' },
  payContent: {
    paddingTop: '0%'  },
  paySectionLabel: { fontSize: 14, fontWeight: '600', color: '#0B1C30', margin: '4%', marginBottom: 12  },
  payLogosRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  payLogoCard: { flex: 1, alignItems: 'center', backgroundColor: '#fff', borderRadius: 12, paddingVertical: 16, paddingHorizontal: 8, marginHorizontal: 4, borderWidth: 2, borderColor: 'transparent' },
  payLogoCardSelected: { borderColor: '#1A72B6' },
  payLogoBadge: { width: 64, height: 40, borderRadius: 6, alignItems: 'center', justifyContent: 'center' },
  payLogoText: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
  payLogoCheck: { position: 'absolute', top: 8, right: 8 },
  payAddBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#31744C', borderRadius: 10, paddingVertical: 14, marginBottom: 20 },
  payAddText: { color: '#fff', fontSize: 15, fontWeight: '600', marginLeft: 6 },
  payEmpty: { color: '#9AA3AE', fontSize: 14, textAlign: 'center', marginTop: 20 },
  payRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 12, padding: 12, marginBottom: 10 },
  payRowBadge: { width: 48, height: 32, borderRadius: 5, alignItems: 'center', justifyContent: 'center' },
  payRowBadgeText: { color: '#fff', fontSize: 9, fontWeight: 'bold' },
  payRowTextWrap: { flex: 1, marginLeft: 12 },
  payRowTitle: { fontSize: 14, fontWeight: '600', color: '#0B1C30' },
  payRowSub: { fontSize: 12, color: '#9AA3AE', marginTop: 2 },
  payRemoveBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },

  // Operators (Djezzy / Mobilis / Ooredoo)
  payBackBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  // Drop shadow: x=4, y=4, blur=5.8, #000000 at 25%
  payOpRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  payOpBtn: { flex: 1, alignItems: 'center', backgroundColor: '#fff', borderRadius: 14, paddingVertical: 18, marginHorizontal: 4, shadowColor: '#000000', shadowOffset: { width: 4, height: 4 }, shadowOpacity: 0.25, shadowRadius: 5.8 },
  // Pressed: drop shadow removed, inner shadow overlay shown instead
  payOpBtnPressed: { shadowOpacity: 0 },
  payOpImgWrap: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  payOpImg: { width: 40, height: 40, resizeMode: 'contain' },
  payOpImgText: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  payOpName: { fontSize: 13, fontWeight: 'bold', color: '#0B1C30', marginTop: 8 },
  payOpChevron: { marginLeft: 'auto' },
  // Inner shadow simulation (same params: #000000 at 25%)
  payOpInnerShadow: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, borderRadius: 14, backgroundColor: 'rgba(0,0,0,0.25)' },

  // Saved numbers list
  payNumRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 12, padding: 14, marginBottom: 10 },
  payNumBadge: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  payNumBadgeText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  payNumText: { flex: 1, fontSize: 16, fontWeight: '600', color: '#0B1C30' },
  payNumEdit: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginLeft: 8, backgroundColor: '#F2F6FC' },
  payNumDelete: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginLeft: 8, backgroundColor: '#FDE8E8' },
  payAddNumBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#31744C', borderRadius: 10, paddingVertical: 14, margin: 20 },

  // Add / edit form
  payFormInput: { width: '100%', borderWidth: 1, borderColor: '#ccc', borderRadius: 8, paddingVertical: 14, paddingHorizontal: 16, fontSize: 18, textAlign: 'center', marginTop: 16 },
  payFormSave: { backgroundColor: '#31744C', borderRadius: 10, paddingVertical: 14, marginTop: 20, alignItems: 'center' },
  payFormSaveText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  payFormCancel: { backgroundColor: '#F2F2F2', borderRadius: 10, paddingVertical: 12, marginTop: 10, alignItems: 'center' },
  payFormCancelText: { color: '#434655', fontSize: 15, fontWeight: '600' },

  // Recharge screen
  rcBalanceWrap: { alignItems: 'center', justifyContent: 'center', marginVertical: 8 },
  rcBalanceCenter: { position: 'absolute', alignItems: 'center' },
  rcBalanceLabel: { fontSize: 12, color: '#9AA3AE', fontWeight: '600', letterSpacing: 1 },
  rcBalanceValue: { fontSize: 34, fontWeight: 'bold', color: '#0B1C30', marginTop: 2 },
  rcBalanceUnit: { fontSize: 14, color: '#434655', marginTop: 2 },
  rcNumRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 2, borderColor: 'transparent' },
  rcNumRowSelected: { borderColor: '#1A72B6' },
  rcRadio: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: '#C4C9D0', alignItems: 'center', justifyContent: 'center', marginLeft: 8 },
  rcRadioSelected: { borderColor: '#1A72B6' },
  rcRadioDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#1A72B6' },
  rcConfirmBtn: { backgroundColor: '#31744C', borderRadius: 10, paddingVertical: 16, alignItems: 'center', marginTop: 8 },
  rcConfirmText: { color: '#fff', fontSize: 16, fontWeight: '600' },
});
